<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Hospital.Domain\Hospital.Domain.csproj" />
    <ProjectReference Include="..\Hospital.Application\Hospital.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.18" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
